### ISSUE TITLE
Request permission to push changes to repo

### ISSUE THREAD

**Issue by tl-fredwintan** [not-a-bank/open-banking-tracker-data#440]
Unsure if this is the correct process but we are trying to update our bank support list but we got the following error when trying to push some code changes:

```
remote: Permission to not-a-bank/open-banking-tracker-data.git denied to tl-fredwintan.
fatal: unable to access 'https://github.com/not-a-bank/open-banking-tracker-data.git/': The requested URL returned error: 403
```

Username:
tl-fredwintan
LizaShTrueLayer

If you need any other information please let me know

**Comment by Gdewilde** [comment]
Hi Fred,
You need to fork the repo first.

**Comment by tl-fredwintan** [comment]
@Gdewilde thank you!
