### ISSUE TITLE
Getting error when opening the PayPal page

### ISSUE THREAD

**Issue by anastasiamonosienco** [not-a-bank/open-banking-tracker-data#451]
- Bank's name: Paypal
- The accessed link: https://www.openbankingtracker.com/provider/paypal
- Screenshots: 
<details>
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/92586216/157862604-73b15053-2590-468b-a43d-4ddbebd8bacc.png">

<img width="855" alt="image" src="https://user-images.githubusercontent.com/92586216/157862651-e1c0c5d1-5c18-42a1-8855-7912136aa9b2.png">
</details>

**Comment by Gdewilde** [comment]
Fixed!
